// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/select": {
    params: {};
  };
  "/query": {
    params: {};
  };
  "/vector": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/upload" | "/select" | "/query" | "/vector";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/select.tsx": {
    id: "routes/select";
    page: "/select";
  };
  "routes/query.tsx": {
    id: "routes/query";
    page: "/query";
  };
  "routes/vector.tsx": {
    id: "routes/vector";
    page: "/vector";
  };
};